/* date = May 15th 2023 9:45 pm */

#ifndef TWEAK_H
#define TWEAK_H

#define DEFAULT_ORBIT_CAMERA_LOOK_SPEED 2.0f
#define DEFAULT_FLY_CAMERA_LOOK_SPEED 0.1f
#define DEFAULT_FLY_CAMERA_MOVE_SPEED 2.0f

#endif //TWEAK_H
